services:
  zenoh-bridge-turtlebot4:
    image: rodrigo55/zenoh-bridge-ros2dds:turtlebot4
    container_name: zenoh-bridge-turtlebot4
    build:
      context: .
    network_mode: "host"
    volumes:
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml
    # environment:
    #   - CYCLONEDDS_URI=file:///var/lib/theconstruct.rrl/cyclonedds.xml
