services:
  zenoh-bridge-turtlebot4:
    image: rodrigo55/zenoh-bridge-ros2dds:turtlebot4
    container_name: zenoh-bridge-turtlebot4
    build:
      context: .
    network_mode: "host"
    environment:
      - RPI4_IP=192.168.2.63 # Replace with your actual Raspberry Pi IP address
    volumes:
      - /var/lib/theconstruct.rrl/cyclonedds.xml:/var/lib/theconstruct.rrl/cyclonedds.xml # The Construct RRL XML config file
